# Import Catppuccin Mocha Theme
import = [
  "~/.config/alacritty/catppuccin-mocha.toml",
]

# Set true color
[env]
TERM = "xterm-256color"

# Set window padding
[window]
padding = { x = 12, y = 12 }

# Font settings
[font]
normal = { family = "CaskaydiaCove Nerd Font", style = "Regular" }
size = 12.0

